# Human Activity Recognition

In [26]:
# Importing libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as py
import seaborn as sns

### Preprocessing Train dataset

In [48]:
# Importing the Train dataset

train = pd.read_csv("train.csv",index_col=None)

In [49]:
# Displaying first 5 rows 

train.head()

tBodyAccmeanX  tBodyAccmeanY  tBodyAccmeanZ  tBodyAccstdX  tBodyAccstdY  \
0       0.288585      -0.020294      -0.132905     -0.995279     -0.983111   
1       0.278419      -0.016411      -0.123520     -0.998245     -0.975300   
2       0.279653      -0.019467      -0.113462     -0.995380     -0.967187   
3       0.279174      -0.026201      -0.123283     -0.996091     -0.983403   
4       0.276629      -0.016570      -0.115362     -0.998139     -0.980817   

   tBodyAccstdZ  tBodyAccmadX  tBodyAccmadY  tBodyAccmadZ  tBodyAccmaxX  ...  \
0     -0.913526     -0.995112     -0.983185     -0.923527     -0.934724  ...   
1     -0.960322     -0.998807     -0.974914     -0.957686     -0.943068  ...   
2     -0.978944     -0.996520     -0.963668     -0.977469     -0.938692  ...   
3     -0.990675     -0.997099     -0.982750     -0.989302     -0.938692  ...   
4     -0.990482     -0.998321     -0.979672     -0.990441     -0.942469  ...   

   angletBodyAccMeangravity  angletBodyAccJerkMeangravityMean  \
0                 -0.112754                          0.030400   
1                  0.053477                         -0.007435   
2                 -0.118559                          0.177899   
3                 -0.036788                         -0.012892   
4                  0.123320                          0.122542   

   angletBodyGyroMeangravityMean  angletBodyGyroJerkMeangravityMean  \
0                      -0.464761                          -0.018446   
1                      -0.732626                           0.703511   
2                       0.100699                           0.808529   
3                       0.640011                          -0.485366   
4                       0.693578                          -0.615971   

   angleXgravityMean  angleYgravityMean  angleZgravityMean  subject  Activity  \
0          -0.841247           0.179941          -0.058627        1         5   
1          -0.844788           0.180289          -0.054317        1         5   
2          -0.848933           0.180637          -0.049118        1         5   
3          -0.848649           0.181935          -0.047663        1         5   
4          -0.847865           0.185151          -0.043892        1         5   

   ActivityName  
0      STANDING  
1      STANDING  
2      STANDING  
3      STANDING  
4      STANDING  

[5 rows x 564 columns]

In [50]:
# Finding the rows and columns
print("Shape of the test dataset:")
print(train.shape)
print()

# Displaying datatypes of columns
print("Datatypes of features:")
print(train.dtypes)

Shape of the test dataset:
(7352, 564)

Datatypes of features:
tBodyAccmeanX        float64
tBodyAccmeanY        float64
tBodyAccmeanZ        float64
tBodyAccstdX         float64
tBodyAccstdY         float64
                      ...   
angleYgravityMean    float64
angleZgravityMean    float64
subject                int64
Activity               int64
ActivityName          object
Length: 564, dtype: object


In [51]:
# Finding missing values

train.isnull().sum()

tBodyAccmeanX        0
tBodyAccmeanY        0
tBodyAccmeanZ        0
tBodyAccstdX         0
tBodyAccstdY         0
                    ..
angleYgravityMean    0
angleZgravityMean    0
subject              0
Activity             0
ActivityName         0
Length: 564, dtype: int64

In [52]:
# Displaying descriptive statistics 

train.describe()
#train.describe(include=all)

tBodyAccmeanX  tBodyAccmeanY  tBodyAccmeanZ  tBodyAccstdX  \
count    7352.000000    7352.000000    7352.000000   7352.000000   
mean        0.274488      -0.017695      -0.109141     -0.605438   
std         0.070261       0.040811       0.056635      0.448734   
min        -1.000000      -1.000000      -1.000000     -1.000000   
25%         0.262975      -0.024863      -0.120993     -0.992754   
50%         0.277193      -0.017219      -0.108676     -0.946196   
75%         0.288461      -0.010783      -0.097794     -0.242813   
max         1.000000       1.000000       1.000000      1.000000   

       tBodyAccstdY  tBodyAccstdZ  tBodyAccmadX  tBodyAccmadY  tBodyAccmadZ  \
count   7352.000000   7352.000000   7352.000000   7352.000000   7352.000000   
mean      -0.510938     -0.604754     -0.630512     -0.526907     -0.606150   
std        0.502645      0.418687      0.424073      0.485942      0.414122   
min       -0.999873     -1.000000     -1.000000     -1.000000     -1.000000   
25%       -0.978129     -0.980233     -0.993591     -0.978162     -0.980251   
50%       -0.851897     -0.859365     -0.950709     -0.857328     -0.857143   
75%       -0.034231     -0.262415     -0.292680     -0.066701     -0.265671   
max        0.916238      1.000000      1.000000      0.967664      1.000000   

       tBodyAccmaxX  ...  fBodyBodyGyroJerkMagkurtosis  \
count   7352.000000  ...                   7352.000000   
mean      -0.468604  ...                     -0.625294   
std        0.544547  ...                      0.307584   
min       -1.000000  ...                     -0.999765   
25%       -0.936219  ...                     -0.845573   
50%       -0.881637  ...                     -0.711692   
75%       -0.017129  ...                     -0.503878   
max        1.000000  ...                      0.956845   

       angletBodyAccMeangravity  angletBodyAccJerkMeangravityMean  \
count               7352.000000                       7352.000000   
mean                   0.008684                          0.002186   
std                    0.336787                          0.448306   
min                   -0.976580                         -1.000000   
25%                   -0.121527                         -0.289549   
50%                    0.009509                          0.008943   
75%                    0.150865                          0.292861   
max                    1.000000                          1.000000   

       angletBodyGyroMeangravityMean  angletBodyGyroJerkMeangravityMean  \
count                    7352.000000                        7352.000000   
mean                        0.008726                          -0.005981   
std                         0.608303                           0.477975   
min                        -1.000000                          -1.000000   
25%                        -0.482273                          -0.376341   
50%                         0.008735                          -0.000368   
75%                         0.506187                           0.359368   
max                         0.998702                           0.996078   

       angleXgravityMean  angleYgravityMean  angleZgravityMean      subject  \
count        7352.000000        7352.000000        7352.000000  7352.000000   
mean           -0.489547           0.058593          -0.056515    17.413085   
std             0.511807           0.297480           0.279122     8.975143   
min            -1.000000          -1.000000          -1.000000     1.000000   
25%            -0.812065          -0.017885          -0.143414     8.000000   
50%            -0.709417           0.182071           0.003181    19.000000   
75%            -0.509079           0.248353           0.107659    26.000000   
max             1.000000           0.478157           1.000000    30.000000   

          Activity  
count  7352.000000  
mean      3.643362  
std       1.744802  
min       1.000000  
25%       2.000000  
50%       4.000000  
75

**ActivityName and Activity have same values, so dropping ActivityName as it has Categorical Values**

In [53]:
train1 = train.drop("ActivityName", axis = 1)

In [54]:
train1.dtypes

tBodyAccmeanX        float64
tBodyAccmeanY        float64
tBodyAccmeanZ        float64
tBodyAccstdX         float64
tBodyAccstdY         float64
                      ...   
angleXgravityMean    float64
angleYgravityMean    float64
angleZgravityMean    float64
subject                int64
Activity               int64
Length: 563, dtype: object

### Preprocessing Test Data

In [55]:
# Importing Test data

test = pd.read_csv("test.csv",index_col=None)

In [56]:
# Displaying first 5 rows

test.head()

tBodyAccmeanX  tBodyAccmeanY  tBodyAccmeanZ  tBodyAccstdX  tBodyAccstdY  \
0       0.257178      -0.023285      -0.014654     -0.938404     -0.920091   
1       0.286027      -0.013163      -0.119083     -0.975415     -0.967458   
2       0.275485      -0.026050      -0.118152     -0.993819     -0.969926   
3       0.270298      -0.032614      -0.117520     -0.994743     -0.973268   
4       0.274833      -0.027848      -0.129527     -0.993852     -0.967445   

   tBodyAccstdZ  tBodyAccmadX  tBodyAccmadY  tBodyAccmadZ  tBodyAccmaxX  ...  \
0     -0.667683     -0.952501     -0.925249     -0.674302     -0.894088  ...   
1     -0.944958     -0.986799     -0.968401     -0.945823     -0.894088  ...   
2     -0.962748     -0.994403     -0.970735     -0.963483     -0.939260  ...   
3     -0.967091     -0.995274     -0.974471     -0.968897     -0.938610  ...   
4     -0.978295     -0.994111     -0.965953     -0.977346     -0.938610  ...   

   angletBodyAccMeangravity  angletBodyAccJerkMeangravityMean  \
0                  0.006462                          0.162920   
1                 -0.083495                          0.017500   
2                 -0.034956                          0.202302   
3                 -0.017067                          0.154438   
4                 -0.002223                         -0.040046   

   angletBodyGyroMeangravityMean  angletBodyGyroJerkMeangravityMean  \
0                      -0.825886                           0.271151   
1                      -0.434375                           0.920593   
2                       0.064103                           0.145068   
3                       0.340134                           0.296407   
4                       0.736715                          -0.118545   

   angleXgravityMean  angleYgravityMean  angleZgravityMean  subject  Activity  \
0          -0.720009           0.276801          -0.057978        2         5   
1          -0.698091           0.281343          -0.083898        2         5   
2          -0.702771           0.280083          -0.079346        2         5   
3          -0.698954           0.284114          -0.077108        2         5   
4          -0.692245           0.290722          -0.073857        2         5   

   ActivityName  
0      STANDING  
1      STANDING  
2      STANDING  
3      STANDING  
4      STANDING  

[5 rows x 564 columns]

In [57]:
# Finding the no.rows and columns
print("Shape of the test dataset:")
print(test.shape)
print()

# Displaying dataypes of columns
print("Datatypes of features:")
print(test.dtypes)

Shape of the test dataset:
(2947, 564)

Datatypes of features:
tBodyAccmeanX        float64
tBodyAccmeanY        float64
tBodyAccmeanZ        float64
tBodyAccstdX         float64
tBodyAccstdY         float64
                      ...   
angleYgravityMean    float64
angleZgravityMean    float64
subject                int64
Activity               int64
ActivityName          object
Length: 564, dtype: object


In [58]:
# Finding missing values

test.isnull().sum()

tBodyAccmeanX        0
tBodyAccmeanY        0
tBodyAccmeanZ        0
tBodyAccstdX         0
tBodyAccstdY         0
                    ..
angleYgravityMean    0
angleZgravityMean    0
subject              0
Activity             0
ActivityName         0
Length: 564, dtype: int64

**ActivityName and Activity have same values, so dropping ActivityName as it has Categorical Values**

In [59]:
test1 = test.drop("ActivityName", axis=1)

In [60]:
test1.shape

(2947, 563)

In [61]:
# Creating X_train, X_test, Y_train, Y_test

X_train = train1.values[:,:-1]
Y_train = train1.values[:,-1]
X_test = test1.values[:,:-1]
Y_test = test1.values[:,-1]

In [62]:
X_train.shape,Y_train.shape, X_test.shape, Y_test.shape

((7352, 562), (7352,), (2947, 562), (2947,))

In [63]:
# Converting float into int

Y_train = Y_train.astype(int)

In [64]:
# Scaling the data

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

scaler.fit(X_train)
X_train = scaler.transform(X_train)

X_test = scaler.transform(X_test)

## Logistic Regression

In [19]:
# Model Building

from sklearn.linear_model import LogisticRegression

# create a model
lr = LogisticRegression()

# fit the model
lr.fit(X_train,Y_train)


C:\Users\windows\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\windows\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [20]:
# Predict

Y_pred = lr.predict(X_test)
Y_pred

array([5, 5, 5, ..., 2, 2, 2])

In [21]:
# Creating a new dataframe to compare the Actual and Predicted values of Activity

df = pd.DataFrame()
df["Activity"] = Y_test
df["Predicted"] = Y_pred

df["Activity"] = df["Activity"].astype(int) 
df.head(70)

Activity  Predicted
0          5          5
1          5          5
2          5          5
3          5          5
4          5          5
..       ...        ...
65         6          6
66         6          6
67         6          6
68         6          6
69         6          6

[70 rows x 2 columns]

In [22]:
# Model Evaluation

from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print("Classification report :")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test,Y_pred)
print("Accuracy of the model:",acc)

[[496   0   0   0   0   0]
 [ 17 453   1   0   0   0]
 [  2   3 415   0   0   0]
 [  0   2   0 424  65   0]
 [  0   0   0  12 520   0]
 [  0   0   0   0  12 525]]
Classification report :
              precision    recall  f1-score   support

         1.0       0.96      1.00      0.98       496
         2.0       0.99      0.96      0.98       471
         3.0       1.00      0.99      0.99       420
         4.0       0.97      0.86      0.91       491
         5.0       0.87      0.98      0.92       532
         6.0       1.00      0.98      0.99       537

    accuracy                           0.96      2947
   macro avg       0.97      0.96      0.96      2947
weighted avg       0.96      0.96      0.96      2947

Accuracy of the model: 0.9613165931455717


In [113]:
#py.figure(figsize=(18,18))
#sns.heatmap(train1.corr(),vmax=1.0, vmin=-1.0,annot=True)
#py.show()

## KNN

In [23]:
from sklearn.neighbors import KNeighborsClassifier

# Create the model
knn = KNeighborsClassifier(n_neighbors=int(round(np.sqrt(len(X_train)),0)),metric="euclidean")

# Fit the model
knn.fit(X_train,Y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='euclidean',
                     metric_params=None, n_jobs=None, n_neighbors=86, p=2,
                     weights='uniform')

In [24]:
# Find the value of n_neighbors
int(round(np.sqrt(len(X_train)),0))

86

In [25]:
# Predict the values

Y_pred = knn.predict(X_test)
Y_pred

array([5, 5, 5, ..., 2, 2, 1])

In [26]:
# Creating a new dataframe to compare the Actual and Predicted values of Activity

df = pd.DataFrame()
df["Activity"] = Y_test
df["Predicted"] = Y_pred

df["Activity"] = df["Activity"].astype(int) 
df.head(70)

Activity  Predicted
0          5          5
1          5          5
2          5          5
3          5          5
4          5          5
..       ...        ...
65         6          6
66         6          6
67         6          6
68         6          6
69         6          6

[70 rows x 2 columns]

In [27]:
# Model Evaluation

from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print("Classification report :")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test,Y_pred)
print("Accuracy of the model:",acc)

[[492   0   4   0   0   0]
 [ 47 423   1   0   0   0]
 [ 84  55 281   0   0   0]
 [  0   3   0 334 153   1]
 [  0   0   0  13 519   0]
 [  0   0   0  10  28 499]]
Classification report :
              precision    recall  f1-score   support

         1.0       0.79      0.99      0.88       496
         2.0       0.88      0.90      0.89       471
         3.0       0.98      0.67      0.80       420
         4.0       0.94      0.68      0.79       491
         5.0       0.74      0.98      0.84       532
         6.0       1.00      0.93      0.96       537

    accuracy                           0.86      2947
   macro avg       0.89      0.86      0.86      2947
weighted avg       0.89      0.86      0.86      2947

Accuracy of the model: 0.8646080760095012


### Tuning KNN

In [ ]:
# Selecting K value manually

from sklearn.metrics import accuracy_score

for K in range(1,31):
    knn = KNeighborsClassifier(K,metric="euclidean")
    knn.fit(X_train,Y_train)
    Y_pred = knn.predict(X_test)
    print ("Accuracy is ", accuracy_score(Y_test,Y_pred), "for K-Value:",K)

Accuracy is  0.8547675602307431 for K-Value: 1
Accuracy is  0.8306752629793009 for K-Value: 2


In [ ]:
from sklearn.metrics import accuracy_score

for K in range(31,91):
    knn = KNeighborsClassifier(K,metric="euclidean")
    knn.fit(X_train,Y_train)
    Y_pred = knn.predict(X_test)
    print ("Accuracy is ", accuracy_score(Y_test,Y_pred), "for K-Value:",K)

**K=9 gives the highest accuracy**

In [28]:
# K = 9

from sklearn.neighbors import KNeighborsClassifier

# Create the model
knn = KNeighborsClassifier(n_neighbors=9,metric="euclidean")

# Fit the model
knn.fit(X_train,Y_train)

# Prediction
Y_pred = knn.predict(X_test)
Y_pred

array([5, 5, 5, ..., 2, 2, 1])

In [29]:
# Model Evaluation

from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print("Classification report :")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test,Y_pred)
print("Accuracy of the model:",acc)

[[487   2   7   0   0   0]
 [ 46 424   1   0   0   0]
 [ 56  48 316   0   0   0]
 [  0   2   0 384 102   3]
 [  0   0   0  21 511   0]
 [  0   0   0  16  10 511]]
Classification report :
              precision    recall  f1-score   support

         1.0       0.83      0.98      0.90       496
         2.0       0.89      0.90      0.90       471
         3.0       0.98      0.75      0.85       420
         4.0       0.91      0.78      0.84       491
         5.0       0.82      0.96      0.88       532
         6.0       0.99      0.95      0.97       537

    accuracy                           0.89      2947
   macro avg       0.90      0.89      0.89      2947
weighted avg       0.90      0.89      0.89      2947

Accuracy of the model: 0.8934509670851714


## Decision Tree 

In [30]:
from sklearn.tree import DecisionTreeClassifier

# Create the model
dt = DecisionTreeClassifier(criterion="gini", random_state=10)

# Fit the model
dt.fit(X_train,Y_train)

# Predict
Y_pred = dt.predict(X_test)
Y_pred

array([5, 5, 5, ..., 2, 1, 2])

In [31]:
# Model Evaluation

from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print("Classification report :")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test,Y_pred)
print("Accuracy of the model:",acc)

[[457  22  17   0   0   0]
 [ 73 371  27   0   0   0]
 [ 16  56 348   0   0   0]
 [  0   0   0 373 118   0]
 [  0   0   0  74 458   0]
 [  0   0   0   0   0 537]]
Classification report :
              precision    recall  f1-score   support

         1.0       0.84      0.92      0.88       496
         2.0       0.83      0.79      0.81       471
         3.0       0.89      0.83      0.86       420
         4.0       0.83      0.76      0.80       491
         5.0       0.80      0.86      0.83       532
         6.0       1.00      1.00      1.00       537

    accuracy                           0.86      2947
   macro avg       0.86      0.86      0.86      2947
weighted avg       0.86      0.86      0.86      2947

Accuracy of the model: 0.8632507634882932


## Pruned DecisionTree

In [32]:
from sklearn.tree import DecisionTreeClassifier

# Create the model
dt2 = DecisionTreeClassifier(criterion="gini",random_state=10,max_depth=15,min_samples_leaf=120)

# Fit the model
dt2.fit(X_train,Y_train)

# Predict
Y_pred=dt.predict(X_test)

In [33]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print("Classification report :")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test,Y_pred)
print("Accuracy of the model:",acc)

[[457  22  17   0   0   0]
 [ 73 371  27   0   0   0]
 [ 16  56 348   0   0   0]
 [  0   0   0 373 118   0]
 [  0   0   0  74 458   0]
 [  0   0   0   0   0 537]]
Classification report :
              precision    recall  f1-score   support

         1.0       0.84      0.92      0.88       496
         2.0       0.83      0.79      0.81       471
         3.0       0.89      0.83      0.86       420
         4.0       0.83      0.76      0.80       491
         5.0       0.80      0.86      0.83       532
         6.0       1.00      1.00      1.00       537

    accuracy                           0.86      2947
   macro avg       0.86      0.86      0.86      2947
weighted avg       0.86      0.86      0.86      2947

Accuracy of the model: 0.8632507634882932


## RandomForest Classifier

In [19]:
from sklearn.ensemble import RandomForestClassifier

rfc = RandomForestClassifier(n_estimators=101)

rfc.fit(X_train,Y_train)

Y_pred = rfc.predict(X_test)
Y_pred


array([5, 5, 5, ..., 2, 1, 1])

In [20]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print("Classification report :")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test,Y_pred)
print("Accuracy of the model:",acc)

[[479   7  10   0   0   0]
 [ 37 425   9   0   0   0]
 [ 17  41 362   0   0   0]
 [  0   0   0 443  48   0]
 [  0   0   0  43 489   0]
 [  0   0   0   0   0 537]]
Classification report :
              precision    recall  f1-score   support

         1.0       0.90      0.97      0.93       496
         2.0       0.90      0.90      0.90       471
         3.0       0.95      0.86      0.90       420
         4.0       0.91      0.90      0.91       491
         5.0       0.91      0.92      0.91       532
         6.0       1.00      1.00      1.00       537

    accuracy                           0.93      2947
   macro avg       0.93      0.93      0.93      2947
weighted avg       0.93      0.93      0.93      2947

Accuracy of the model: 0.9280624363759755


## Support Vector Machine 

In [46]:
from sklearn import svm

svc = svm.SVC(kernel="linear",C=1.0,gamma=0.1)

svc.fit(X_train,Y_train)

Y_pred = svc.predict(X_test)

In [47]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print("Classification report :")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test,Y_pred)
print("Accuracy of the model:",acc)

[[495   0   1   0   0   0]
 [ 16 453   2   0   0   0]
 [  6  15 399   0   0   0]
 [  0   2   0 423  66   0]
 [  0   0   0  19 513   0]
 [  0   0   0   0   0 537]]
Classification report :
              precision    recall  f1-score   support

         1.0       0.96      1.00      0.98       496
         2.0       0.96      0.96      0.96       471
         3.0       0.99      0.95      0.97       420
         4.0       0.96      0.86      0.91       491
         5.0       0.89      0.96      0.92       532
         6.0       1.00      1.00      1.00       537

    accuracy                           0.96      2947
   macro avg       0.96      0.96      0.96      2947
weighted avg       0.96      0.96      0.96      2947

Accuracy of the model: 0.9569053274516457


## Gaussian Naive Bayes

In [65]:
from sklearn.naive_bayes import GaussianNB

nb = GaussianNB()

nb.fit(X_train,Y_train)

Y_pred = nb.predict(X_test)

In [66]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print("Classification report :")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test,Y_pred)
print("Accuracy of the model:",acc)

[[416  38  42   0   0   0]
 [  9 451  11   0   0   0]
 [ 80  83 257   0   0   0]
 [  0   7   0 368 111   5]
 [  0  15   0  54 455   8]
 [  0   3   0 211   0 323]]
Classification report :
              precision    recall  f1-score   support

         1.0       0.82      0.84      0.83       496
         2.0       0.76      0.96      0.84       471
         3.0       0.83      0.61      0.70       420
         4.0       0.58      0.75      0.65       491
         5.0       0.80      0.86      0.83       532
         6.0       0.96      0.60      0.74       537

    accuracy                           0.77      2947
   macro avg       0.79      0.77      0.77      2947
weighted avg       0.79      0.77      0.77      2947

Accuracy of the model: 0.7702748557855447


## Comparing accuracy

In [68]:
import plotly.graph_objects as go

fig = go.Figure(data=[go.Table(
    header=dict(values=['Model', 'Accuracy'],
                line_color='darkslategray',
                fill_color='lightskyblue',
                align='left'),
    cells=dict(values=[["Logistic Regression","KNN","Tuned KNN","Decision Tree","Pruned Decision Tree","Random Forest","Support Vector Machine","Gaussian Naive Bayes"], # 1st column
                       [96.13, 86.46, 89.34, 86.32, 86.32, 92.80,95.60,77.02]], # 2nd column
               line_color='darkslategray',
               fill_color='lightcyan',
               align='left'))
])

fig.update_layout(width=500, height=380)
fig.show()

## From the above table we understand that Logistic Regression gives the highest accuracy 